### ISSUE TITLE
PostgreQueryBuilder.distinct_on is not a function

### ISSUE THREAD

**Issue by bikeshedder** [kayak/pypika#518]
It seams that `distinct_on` no longer works as explained in #356 

```
$ python
Python 3.8.2 (default, May 13 2020, 15:52:37) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypika import PostgreSQLQuery
>>> q = PostgreSQLQuery.from_('customers').select('id', 'fname', 'lname', 'phone').distinct_on("fname").orderby("fname", "id")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Field' object is not callable
```

Further investigation shows:

```
$ python
Python 3.8.2 (default, May 13 2020, 15:52:37) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypika import PostgreSQLQuery
>>> type(PostgreSQLQuery.from_('x').distinct_on)
<class 'pypika.terms.Field'>
```

**Comment by bikeshedder** [comment]
Oh my... I finally figured it out. For some reason I was still running PyPika 0.27.2. I recently reinstalled it but didn't realize it was using a pinned version. :facepalm: 

Using the correct version of PyPika it works now. :+1:

**Comment by jpjagt** [comment]
for anyone encountering the same issue, in my case, i got the same error, but this was because i was using `ppk.Query.from_('x').distinct_on` and not the postgresql dialect: `ppk.PostgreSQLQuery.from_('x').distinct_on`.

`DISTINCT ON` is only available in postgresql.
